In [1]:
import numpy as p

In [2]:
p.__version__

'2.1.3'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
arr = p.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
p.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
p.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
p.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
p.arange(20,10)

array([], dtype=int64)

In [17]:
p.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
p.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
p.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [22]:
p.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [24]:
p.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
p.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
p.ones(2)

array([1., 1.])

In [28]:
p.ones(2,dtype=int)

array([1, 1])

In [30]:
p.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [31]:
p.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
arr

array([0, 1, 2, 3, 4, 5])

In [33]:
ran(3,2)

NameError: name 'ran' is not defined

In [34]:
random.rand(3,2)

NameError: name 'random' is not defined

In [37]:
p.random.rand(3)

array([0.31828408, 0.1756205 , 0.40791837])

In [39]:
p.random.randint(4,6)

5

In [41]:
p.random.randint(0,3)

1

In [42]:
p.random.randint(2,8,3)

array([4, 7, 7], dtype=int32)

In [51]:
b = p.random.randint(10,40,(8,10))

In [52]:
b

array([[29, 39, 17, 11, 33, 38, 11, 17, 34, 22],
       [11, 30, 31, 31, 22, 37, 27, 39, 22, 20],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [21, 29, 35, 27, 34, 20, 33, 32, 20, 38],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35],
       [16, 28, 19, 32, 38, 14, 38, 23, 11, 23],
       [26, 10, 21, 12, 37, 11, 27, 15, 18, 39],
       [17, 20, 20, 23, 13, 29, 39, 30, 32, 16]], dtype=int32)

In [53]:
b[0]

array([29, 39, 17, 11, 33, 38, 11, 17, 34, 22], dtype=int32)

In [56]:
print(b[1,-2])

22


In [57]:
b[::-1]

array([[17, 20, 20, 23, 13, 29, 39, 30, 32, 16],
       [26, 10, 21, 12, 37, 11, 27, 15, 18, 39],
       [16, 28, 19, 32, 38, 14, 38, 23, 11, 23],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35],
       [21, 29, 35, 27, 34, 20, 33, 32, 20, 38],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [11, 30, 31, 31, 22, 37, 27, 39, 22, 20],
       [29, 39, 17, 11, 33, 38, 11, 17, 34, 22]], dtype=int32)

In [58]:
b[:-1]

array([[29, 39, 17, 11, 33, 38, 11, 17, 34, 22],
       [11, 30, 31, 31, 22, 37, 27, 39, 22, 20],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [21, 29, 35, 27, 34, 20, 33, 32, 20, 38],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35],
       [16, 28, 19, 32, 38, 14, 38, 23, 11, 23],
       [26, 10, 21, 12, 37, 11, 27, 15, 18, 39]], dtype=int32)

In [59]:
type(b)

numpy.ndarray

In [61]:
b

array([[29, 39, 17, 11, 33, 38, 11, 17, 34, 22],
       [11, 30, 31, 31, 22, 37, 27, 39, 22, 20],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [21, 29, 35, 27, 34, 20, 33, 32, 20, 38],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35],
       [16, 28, 19, 32, 38, 14, 38, 23, 11, 23],
       [26, 10, 21, 12, 37, 11, 27, 15, 18, 39],
       [17, 20, 20, 23, 13, 29, 39, 30, 32, 16]], dtype=int32)

In [63]:
b[::2]

array([[29, 39, 17, 11, 33, 38, 11, 17, 34, 22],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35],
       [26, 10, 21, 12, 37, 11, 27, 15, 18, 39]], dtype=int32)

In [66]:
b


array([[29, 39, 17, 11, 33, 38, 11, 17, 34, 22],
       [11, 30, 31, 31, 22, 37, 27, 39, 22, 20],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [21, 29, 35, 27, 34, 20, 33, 32, 20, 38],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35],
       [16, 28, 19, 32, 38, 14, 38, 23, 11, 23],
       [26, 10, 21, 12, 37, 11, 27, 15, 18, 39],
       [17, 20, 20, 23, 13, 29, 39, 30, 32, 16]], dtype=int32)

In [67]:
b[0]

array([29, 39, 17, 11, 33, 38, 11, 17, 34, 22], dtype=int32)

In [69]:
b


array([[29, 39, 17, 11, 33, 38, 11, 17, 34, 22],
       [11, 30, 31, 31, 22, 37, 27, 39, 22, 20],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [21, 29, 35, 27, 34, 20, 33, 32, 20, 38],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35],
       [16, 28, 19, 32, 38, 14, 38, 23, 11, 23],
       [26, 10, 21, 12, 37, 11, 27, 15, 18, 39],
       [17, 20, 20, 23, 13, 29, 39, 30, 32, 16]], dtype=int32)

In [70]:
b[0:5]

array([[29, 39, 17, 11, 33, 38, 11, 17, 34, 22],
       [11, 30, 31, 31, 22, 37, 27, 39, 22, 20],
       [27, 16, 37, 29, 14, 13, 39, 37, 16, 28],
       [21, 29, 35, 27, 34, 20, 33, 32, 20, 38],
       [10, 36, 33, 19, 31, 13, 26, 31, 34, 35]], dtype=int32)

In [80]:
b[0,5]

np.int32(38)

In [79]:
b[5,-3]

np.int32(23)

In [82]:
p.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
p.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [85]:
p.random.randint[20,30]

TypeError: 'method' object is not subscriptable

In [86]:
h = p.random.randint(20,50,(20,30))

In [87]:
h

array([[47, 38, 26, 29, 41, 47, 35, 24, 23, 26, 20, 20, 32, 37, 37, 30,
        48, 44, 20, 25, 41, 48, 39, 31, 27, 25, 35, 31, 34, 42],
       [22, 33, 44, 37, 27, 47, 37, 44, 35, 41, 22, 43, 49, 49, 40, 46,
        49, 46, 44, 20, 35, 33, 25, 30, 43, 43, 24, 23, 27, 29],
       [38, 26, 36, 47, 41, 38, 22, 24, 40, 33, 43, 29, 36, 46, 36, 26,
        25, 36, 30, 36, 49, 37, 33, 47, 47, 44, 30, 46, 32, 22],
       [35, 45, 44, 24, 39, 23, 47, 37, 23, 25, 26, 42, 40, 32, 21, 30,
        47, 20, 35, 32, 47, 31, 29, 21, 27, 45, 22, 37, 29, 23],
       [28, 24, 39, 39, 39, 26, 43, 27, 28, 24, 38, 28, 37, 28, 38, 44,
        41, 24, 42, 32, 38, 28, 40, 30, 45, 28, 45, 38, 37, 31],
       [21, 23, 38, 23, 36, 40, 38, 39, 38, 41, 48, 43, 28, 35, 46, 49,
        21, 27, 43, 23, 28, 39, 47, 48, 49, 48, 48, 35, 42, 24],
       [48, 48, 24, 26, 24, 40, 33, 40, 35, 28, 37, 34, 42, 24, 22, 23,
        31, 26, 25, 47, 27, 33, 25, 35, 33, 42, 47, 34, 23, 28],
       [43, 32, 28, 40, 25, 27, 30, 37, 2

In [88]:
h.shape

(20, 30)

In [89]:
h.size

600

In [91]:
h = p.full((10,20),40)

In [92]:
h

array([[40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40]])